import { Header } from '@/components/Header';
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { SearchParams } from '@/types';
import { Footer } from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  searchParams
}: {
  children: React.ReactNode
  searchParams: SearchParams
}) {
  return (
    <html lang="en">
      <body className={`w-full h-screen ${inter.className}`}>
        <Header searchParams={searchParams} />
        {children}
        <Footer />
      </body>
    </html>
  )
}
